package fr.utbm.lo54.entity;
// Generated 12 avr. 2018 21:08:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String code;
     private String title;
     private Set courseSessions = new HashSet(0);
     private Set courseSessions_1 = new HashSet(0);

    public Course() {
    }

	
    public Course(String code, String title) {
        this.code = code;
        this.title = title;
    }
    public Course(String code, String title, Set courseSessions, Set courseSessions_1) {
       this.code = code;
       this.title = title;
       this.courseSessions = courseSessions;
       this.courseSessions_1 = courseSessions_1;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getCourseSessions() {
        return this.courseSessions;
    }
    
    public void setCourseSessions(Set courseSessions) {
        this.courseSessions = courseSessions;
    }
    public Set getCourseSessions_1() {
        return this.courseSessions_1;
    }
    
    public void setCourseSessions_1(Set courseSessions_1) {
        this.courseSessions_1 = courseSessions_1;
    }




}


