package fr.utbm.lo54.entity;
// Generated 12 avr. 2018 21:08:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;

/**
 * CourseSession generated by hbm2java
 */
public class CourseSession  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Location location;
     private Date startDate;
     private Date endDate;
     private int max;

    public CourseSession() {
    }

	
    public CourseSession(Course course, Location location, Date startDate, Date endDate, int max) {
        this.course = course;
        this.location = location;
        this.startDate = startDate;
        this.endDate = endDate;
        this.max = max;
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public int getMax() {
        return this.max;
    }
    
    public void setMax(int max) {
        this.max = max;
    }


}


